// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourAgencyApp.Models;

#nullable disable

namespace TourAgencyApp.Migrations
{
    [DbContext(typeof(TourAgencyDbContext))]
    partial class TourAgencyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelPhoto", b =>
                {
                    b.Property<int>("HotelsID")
                        .HasColumnType("int");

                    b.Property<int>("PhotosID")
                        .HasColumnType("int");

                    b.HasKey("HotelsID", "PhotosID");

                    b.HasIndex("PhotosID");

                    b.ToTable("HotelPhoto");
                });

            modelBuilder.Entity("PhotoTour", b =>
                {
                    b.Property<int>("PhotosID")
                        .HasColumnType("int");

                    b.Property<int>("ToursID")
                        .HasColumnType("int");

                    b.HasKey("PhotosID", "ToursID");

                    b.HasIndex("ToursID");

                    b.ToTable("PhotoTour");
                });

            modelBuilder.Entity("TourAgencyApp.Models.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("TourAgencyApp.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronimyc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhotoID")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PhotoID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TourAgencyApp.Models.Hotel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("TourAgencyApp.Models.Photo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<byte[]>("PhotoValue")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ID");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("TourAgencyApp.Models.Tour", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("money");

                    b.Property<int?>("CountyID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("HotelID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<bool>("IsConducted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnTour")
                        .HasColumnType("bit");

                    b.Property<int>("MaxTouristCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponsibleEmployeeID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<int?>("TransoprtTypeID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CountyID");

                    b.HasIndex("HotelID");

                    b.HasIndex("ResponsibleEmployeeID");

                    b.HasIndex("TransoprtTypeID");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("TourAgencyApp.Models.Tourist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronimyc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhotoID")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PhotoID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("TourAgencyApp.Models.Transport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Transports");
                });

            modelBuilder.Entity("TourAgencyApp.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TourTourists", b =>
                {
                    b.Property<int>("ClientToursID")
                        .HasColumnType("int");

                    b.Property<int>("TouristsID")
                        .HasColumnType("int");

                    b.HasKey("ClientToursID", "TouristsID");

                    b.HasIndex("TouristsID");

                    b.ToTable("TourTourists");
                });

            modelBuilder.Entity("HotelPhoto", b =>
                {
                    b.HasOne("TourAgencyApp.Models.Hotel", null)
                        .WithMany()
                        .HasForeignKey("HotelsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourAgencyApp.Models.Photo", null)
                        .WithMany()
                        .HasForeignKey("PhotosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhotoTour", b =>
                {
                    b.HasOne("TourAgencyApp.Models.Photo", null)
                        .WithMany()
                        .HasForeignKey("PhotosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourAgencyApp.Models.Tour", null)
                        .WithMany()
                        .HasForeignKey("ToursID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TourAgencyApp.Models.Employee", b =>
                {
                    b.HasOne("TourAgencyApp.Models.Photo", "Photo")
                        .WithMany("Employees")
                        .HasForeignKey("PhotoID");

                    b.HasOne("TourAgencyApp.Models.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("TourAgencyApp.Models.Employee", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TourAgencyApp.Models.Tour", b =>
                {
                    b.HasOne("TourAgencyApp.Models.Country", "Country")
                        .WithMany("Tours")
                        .HasForeignKey("CountyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourAgencyApp.Models.Hotel", "Hotel")
                        .WithMany("Tours")
                        .HasForeignKey("HotelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourAgencyApp.Models.Employee", "ResponsibleEmployee")
                        .WithMany("Tours")
                        .HasForeignKey("ResponsibleEmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourAgencyApp.Models.Transport", "TransoprtType")
                        .WithMany("Tours")
                        .HasForeignKey("TransoprtTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Hotel");

                    b.Navigation("ResponsibleEmployee");

                    b.Navigation("TransoprtType");
                });

            modelBuilder.Entity("TourAgencyApp.Models.Tourist", b =>
                {
                    b.HasOne("TourAgencyApp.Models.Photo", "Photo")
                        .WithMany("Clients")
                        .HasForeignKey("PhotoID");

                    b.HasOne("TourAgencyApp.Models.User", "User")
                        .WithOne("Client")
                        .HasForeignKey("TourAgencyApp.Models.Tourist", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TourTourists", b =>
                {
                    b.HasOne("TourAgencyApp.Models.Tour", null)
                        .WithMany()
                        .HasForeignKey("ClientToursID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourAgencyApp.Models.Tourist", null)
                        .WithMany()
                        .HasForeignKey("TouristsID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TourAgencyApp.Models.Country", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("TourAgencyApp.Models.Employee", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("TourAgencyApp.Models.Hotel", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("TourAgencyApp.Models.Photo", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("TourAgencyApp.Models.Transport", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("TourAgencyApp.Models.User", b =>
                {
                    b.Navigation("Client");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
